const test=require('node:test'),assert=require('node:assert/strict'),S=require('../course-workspace/store.js'),G=require('../course-workspace/greenbook.js'),W=require('../course-workspace/workflow.js'),HD=require('../course-workspace/hd-map.js');
const storage=new Map();global.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
function course(){const c=S.blank('Test',[121,31],2);c.project_id='local-test';c.source_import={type:'greenbook_public',venue_id:'cn0000999'};return c;}
test('same venue resumes without overwriting local edits, explicit copy only creates another',()=>{storage.clear();const c=course(),id=G.importLocal(c);const edited=S.read(id);edited.holes[0].device_points=[{id:'mine',coordinate:[121,31],name:'keep'}];S.save(id,edited);assert.equal(G.importLocal(course()),id);assert.equal(S.custom().length,1);assert.equal(S.read(id).holes[0].device_points[0].id,'mine');const copy=G.importLocal(c,{forceNew:true});assert.notEqual(copy,id);assert.equal(S.custom().length,2);assert.equal(c.project_id,'local-test');});
test('same names do not merge unrelated venue IDs; latest stored project comes first',()=>{storage.clear();const c=course();S.register('older',c);const d=structuredClone(c);d.source_import.venue_id='cn0000998';S.register('other',d);S.register('newer',c);const a=S.read('older'),b=S.read('newer');a.updated_at='2025-01-01T00:00:00Z';b.updated_at='2026-01-01T00:00:00Z';localStorage.setItem(S.key('older'),JSON.stringify(a));localStorage.setItem(S.key('newer'),JSON.stringify(b));assert.deepEqual(G.existing('cn0000999').map(r=>r.id),['newer','older']);assert.deepEqual(G.existing('cn0000998').map(r=>r.id),['other']);});
test('legacy saved baseline resumes by exact source ID even without custom catalogue entry',()=>{storage.clear();const c=course();delete c.source_import;c.source_project_id='cn0000999';S.save('cn0000999',c);assert.equal(S.custom().length,0);assert.deepEqual(G.existing('cn0000999').map(r=>r.id),['cn0000999']);});
test('empty geometry cannot become ready merely by having an image',()=>{const c=course();c.holes[0].visual={width:100,height:100,controls:[]};const r=W.assess(c);assert.equal(r.renderable,0);assert.equal(r.ready,0);assert.equal(r.holes[0].stage,'missing_geometry');assert.ok(r.holes[0].missing.includes('果岭'));assert.equal(r.field_verified,false);});
test('image freshness and registration form distinct steps, never field verification',()=>{const c=course(),h=c.holes[0];h.fairway=[[121,31],[121.001,31],[121.001,31.001],[121,31.001]];assert.equal(W.assess(c).holes[0].stage,'needs_image');h.visual={width:2000,height:2000,controls:[]};assert.equal(W.assess(c).holes[0].stage,'needs_registration');const p=HD.layout(h,2048);h.visual={generator:'coordinate-hd/1',source_signature:p.source_signature,controls:p.controls};assert.equal(W.assess(c).holes[0].stage,'ready_for_review');h.fairway[0][0]+=.00001;assert.equal(W.assess(c).holes[0].stage,'needs_regeneration');});
test('delivery diff handles additions, edits, removals and metadata without modifying source',async()=>{const c=course(),before=JSON.stringify(c),first=await W.snapshot(c);assert.equal(JSON.stringify(c),before);assert.deepEqual(W.changes(first,null).added,[1,2]);c.holes[0].device_points=[{id:'x',coordinate:[121,31]}];c.holes[1].n=3;c.name='Renamed';const next=await W.snapshot(c),diff=W.changes(next,first);assert.deepEqual(diff.changed,[1]);assert.deepEqual(diff.added,[3]);assert.deepEqual(diff.removed,[2]);assert.equal(diff.metadata_changed,true);});
test('save revision and object key order do not manufacture metadata changes',async()=>{const c=course(),a=await W.snapshot(c);c.revision=23;c.updated_at='changed';const b=await W.snapshot(c);assert.deepEqual(W.changes(b,a).unchanged,[1,2]);assert.equal(W.changes(b,a).metadata_changed,false);assert.equal(W.stable({a:1,b:2}),W.stable({b:2,a:1}));});
test('another project baseline cannot be treated as an update',async()=>{const c=course(),first=await W.snapshot(c);c.project_id='copy';assert.equal(W.changes(await W.snapshot(c),first).first_export,true);});
