/* Extends the existing Geoman editor; all modes retain the SAME Leaflet geometry. */
if(QS.get('workspace')==='1') (function(){
  'use strict';
  const $=id=>document.getElementById(id), PW=HolePointWorkspace;
  const originalSideNodes=[...$('side').children];
  document.body.classList.add('integrated');
  const bar=document.createElement('nav');bar.className='workspace-bar';bar.innerHTML='<a href="../cn/map/">← 地图选球场</a><strong id="workspace-title">逐洞编辑</strong><button id="mode-real" aria-pressed="true">实景地图</button><button id="mode-vector" aria-pressed="false">虚拟地图 · 可编辑</button><button id="mode-hd">高清图 / 配准编辑</button><button id="mode-gps">GPS 测距</button><button id="workspace-save">保存本机数据</button>';
  document.body.prepend(bar);
  function reveal(element){for(let p=element;p&&p!==document.body;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;element.scrollIntoView({block:'nearest'});}
  function selectView(id){for(const key of ['mode-real','mode-vector','mode-hd'])$(key).setAttribute('aria-pressed',String(key===id));}
  const quickHole=document.createElement('select');quickHole.id='workspace-hole';quickHole.setAttribute('aria-label','当前球洞');quickHole.style.width='90px';bar.insertBefore(quickHole,$('mode-real'));quickHole.onchange=()=>{const target=+quickHole.value;if(sync())loadHole(target);};
  const copy=document.createElement('button');copy.id='workspace-copy';copy.textContent='另存副本';bar.append(copy);copy.onclick=()=>{if(!courseData||!sync())return;const id='local-'+crypto.randomUUID(),c=structuredClone(courseData);c.name+=' · 副本';CourseStore.register(id,c);location.href='?'+new URLSearchParams({gb:id,hole:String(curHole),workspace:'1'});};
  const panel=document.createElement('section');panel.className='workspace-tools';panel.innerHTML=`<h2>自由放点与 GPS 测距</h2><p class="hint" id="workspace-quality">坐标与距离精度待实地核验</p>
    <label>新点名称<input id="point-name" placeholder="球车 A / 自定义目标"></label><div class="row"><button id="place-cart">放置球车</button><button id="place-point">放置目标点</button></div>
    <button id="place-pin" class="wide">设置果岭旗位置</button><button id="draw-route" class="wide">绘制本洞球车路线</button><button id="cancel-tool" class="wide">结束放点 / 绘制</button>
    <label>测距起点<select id="distance-from"></select></label><label>测距终点（可跨洞）<select id="distance-to"></select></label><output id="distance-value" class="workspace-distance">— m</output><output id="distance-meta">放置球车，再选择目标。</output>
    <div class="row"><button id="live-start">使用实时 GPS</button><button id="live-stop">停止 GPS</button></div><p class="hint" id="live-status">手动点仅用于测试；未启用设备定位。</p>
    <details><summary>精确输入 / 更新所选起点</summary><label>WGS84 经度<input id="point-lng" type="number" step="any"></label><label>WGS84 纬度<input id="point-lat" type="number" step="any"></label><button id="apply-coordinate">更新坐标</button></details>
    <details><summary>定位质量 / RTK 接入</summary><p>默认只显示声明水平误差半径 ≤ 2 m 且 10 秒内的浏览器定位；不吸附、不平滑伪造精度。RTK 输入还要求固定解和有效差分龄期。坐标系须与 WGS84 地图一致。</p><label>允许的水平误差半径（m）<input id="gnss-limit" type="number" min="0.01" max="100" step="0.1" value="2"></label><label>RTK 设备快照 JSON<textarea id="gnss-input" aria-label="RTK 设备快照 JSON"></textarea></label><button id="gnss-apply">检查并接入 RTK 快照</button><p id="gnss-status" role="status">尚未接入 RTK；设备声明不是测绘认证。</p><a href="../docs/PRECISION-INPUT.md" target="_blank" rel="noopener">数据格式与精度说明</a></details>
    <details><summary>导入 GPS 多车点位</summary><p class="hint">旧版离线快照导入（不做实时质量门槛）；不要当作当前可靠位置。JSON: {positions:[{id,coordinate:[经度,纬度]}]}；或 CSV 列 id,longitude,latitude。只更新本机，不发送坐标给外部服务器。</p><textarea id="telemetry" aria-label="GPS 点位输入"></textarea><button id="apply-telemetry">应用 GPS 点位</button></details>
    <details><summary>导出数据 / 生成虚拟地图</summary><button id="export-points" class="wide">导出全场点位 GeoJSON</button><button id="export-vector" class="wide">生成本洞矢量虚拟图 SVG</button><p class="hint">SVG 依据现有地理要素生成，附原始几何和投影信息；不是重新生成美术图，也不提升源数据的精度。</p></details>`;
  const nodes=document.createElement('details');nodes.innerHTML='<summary>查看当前洞 WGS84 节点</summary><textarea id="node-data" aria-label="当前洞 WGS84 节点" readonly style="height:220px"></textarea>';panel.append(nodes);
  $('side').prepend(panel);
  const generation=createGenerationUI($('side'),{course:()=>courseData,hole:()=>currentHoleData(),sync:()=>sync(),real:()=>$('mode-real').click(),vector:()=>$('mode-vector').click(),download:()=>$('export-vector').click(),gps:()=>$('export-points').click(),draw:async(kind='fairway',n=curHole)=>{if(!['fairway','green','teebox','cartroute'].includes(kind))throw Error('不支持的绘制类型');if(!sync())throw Error('当前编辑保存失败，请先处理');cancel();await closePhoto();imageEditor.close();mapPick=null;if(n!==curHole)loadHole(n);await $('mode-real').onclick();curType=kind;map.pm.enableDraw(kind==='cartroute'?'Line':'Polygon');status('正在补绘第 '+curHole+' 洞的'+({fairway:'球道',green:'果岭',teebox:'发球区',cartroute:'球车路线'}[kind])+'：沿卫星图实际边缘依次点击，点击最后一个节点完成。坐标为影像描绘，未实测。');},apply:c=>{CourseStore.validate(c);CourseStore.save(GB,c);for(const h of c.holes)localStorage.setItem('golfmap.gps-draft.'+GB+'.hole-'+h.n,JSON.stringify({hole_data:h}));courseData=c;restoring=true;loadHole(curHole);restoring=false;refresh();zoomToHole();}});
  const admin=document.createElement('details');admin.className='project-admin';admin.innerHTML='<summary>球场项目 · 保存 / 图片打包 / 检查</summary><label>项目名称<input id="project-name"></label><button id="project-rename">保存项目名称</button><button id="project-pack">下载完整项目包（含图片）</button><p>项目包可在地图页导入成独立副本，包含图片、所有球洞、配准和点位。普通 JSON 备份不包含本机图片文件。</p><div id="project-audit" class="project-audit"></div>';panel.before(admin);
  document.querySelector('#side .sub').textContent='沿用原版点、线、面工具。实景和矢量虚拟地图使用同一份 WGS84 数据；本机保存，不写朋友后台。';
  $('savehole').textContent='✓ 保存当前洞（本机）';$('savesrv').closest('.grp').querySelector('p').textContent='本机保存不会改动 GreenBook 后台；交付客户请导出 JSON 或 GeoJSON。';
  const photo=document.createElement('section');photo.className='workspace-photo';photo.hidden=true;photo.innerHTML='<header><span id="photo-status"></span><button id="photo-close">返回地图编辑</button></header><iframe id="photo-frame" title="高清虚拟图配准编辑"></iframe><main id="photo-main" hidden><img id="photo-img" alt="当前球洞未配准美术草稿"></main>';document.body.append(photo);
  const imagePanel=document.createElement('section');imagePanel.id='generic-image-panel';imagePanel.hidden=true;document.body.append(imagePanel);
  const packPreview=document.createElement('details');packPreview.innerHTML='<summary>查看最近生成的项目包 JSON（小于 2 MB）</summary><textarea id="project-pack-preview" aria-label="项目包 JSON 预览" readonly></textarea>';admin.append(packPreview);
  const legacy=document.createElement('button');legacy.textContent='原有高清编辑（兼容入口）';legacy.hidden=true;admin.append(legacy);legacy.onclick=()=>{if(!sync())return;imageEditor.close();photo.hidden=false;$('photo-status').textContent='旧版兼容编辑 · 不用于新增球场';$('photo-frame').hidden=false;$('photo-main').hidden=true;$('photo-frame').src='../'+courseData.legacy_editor+'?'+new URLSearchParams({gb:GB,draft:'codex',edit:'1',hole:String(curHole)});};
  let mapPick=null;
  function persistImageChange(){CourseStore.save(GB,courseData);localStorage.setItem('golfmap.gps-draft.'+GB+'.hole-'+curHole,JSON.stringify({hole_data:currentHoleData()}));restoring=true;loadHole(curHole);restoring=false;refresh();}
  const imageEditor=createCourseImageEditor(imagePanel,{hole:()=>currentHoleData(),allPoints:()=>catalog.slice(),points:()=>[...catalog.filter(p=>p.hole===curHole),...(live?[{...live,name:'设备实时 GPS',kind:'cart'}]:watch===null&&routePosition?[{...routePosition,name:'路线模拟球车',kind:'cart'}]:[])],live:()=>live?{...live,name:'设备实时 GPS'}:watch===null&&routePosition?{...routePosition,name:'路线模拟（非实测）'}:null,gpsStatus:()=>watch!==null?$('live-status').textContent:'',startGPS:()=>$('live-start').click(),stopGPS:()=>$('live-stop').click(),startSimulation:()=>{$('live-stop').click();$('distance-from').value='route-live';$('cartplay').click();},stopSimulation:()=>$('cartstop').click(),changed:persistImageChange,close:()=>{map.invalidateSize();selectView(vector?'mode-vector':'mode-real');},pick:cb=>{cancel();mapPick=cb;status('请在地图点击与图片相同的地物位置；选中后自动返回图片配准。');},
    place:(kind,c,name)=>{const h=currentHoleData();if(kind==='flag'){h.flag=c;h.pins={...h.pins,mid:c};delete h.green_targets;}else if(['black','gold','blue','white','red'].includes(kind)){h.tees??={};h.tees[kind]=c;if(kind==='black'||!h.tee)h.tee=c;delete h.green_targets;}else{h.device_points??=[];h.device_points.push({id:crypto.randomUUID(),name:name||(kind==='cart'?'球车':'目标点'),kind,coordinate:c,source:'image_registration',accuracy_m:null,updated_at:new Date().toISOString()});}persistImageChange();},
    move:(p,c)=>{const h=currentHoleData();if(p.type==='tee'){h.tees[p.color]=c;if(p.color==='black')h.tee=c;delete h.green_targets;}else if(p.role==='flag'){h.flag=c;h.pins={...h.pins,mid:c};delete h.green_targets;}else{const d=h.device_points?.find(d=>d.id===p.local_id);if(!d)throw Error('此目标由地理几何推导，请在地图上编辑对应区域');for(const k of ['accuracy_confidence','fix_type','correction_age_s','receiver'])delete d[k];Object.assign(d,{coordinate:c,source:'image_registration',accuracy_m:null,updated_at:new Date().toISOString()});}persistImageChange();}});
  map.on('click',e=>{if(mapPick){const cb=mapPick;mapPick=null;cb([e.latlng.lng,e.latlng.lat]);}});
  const production=createProductionUI($('side'),{course:()=>courseData,hole:()=>currentHoleData(),sync,open:()=>{cancel();if(sync())imageEditor.open();},save:c=>{CourseStore.save(GB,c);for(const h of c.holes)localStorage.setItem('golfmap.gps-draft.'+GB+'.hole-'+h.n,JSON.stringify({hole_data:h}));},refresh:()=>refresh()});
  function fold(selector,id,title){const section=document.querySelector(selector),details=document.createElement('details'),summary=document.createElement('summary');details.id=id;details.className='workflow-advanced';summary.textContent=title;section.before(details);details.append(summary,section);return details;}
  const productionDetails=fold('.production-tools','production-options','高清生成、图片版本与实测检查（详细工具）');
  fold('.generation-start','generation-options','公开地图读取与导出（详细工具）');
  const showProduction=()=>{imageEditor.close();selectView(vector?'mode-vector':'mode-real');reveal(productionDetails);};
  async function openHD(){if(production.isBusy())return;cancel();await closePhoto();if(!sync())return;const h=currentHoleData(),owner=courseData;if(!h)return;if(!h.visual){showProduction();$('mode-hd').disabled=true;try{if(!await production.generate(false))return;}finally{$('mode-hd').disabled=false;}}if(courseData!==owner||currentHoleData()?.n!==h.n)return;selectView('mode-hd');await imageEditor.open();}
  const workflow=createWorkflowUI($('side'),{course:()=>courseData,hole:()=>currentHoleData(),sync,source:()=>{reveal($('generation-options'));$('generate-map-data').click();},edit:()=>{$('mode-real').click();reveal($('simple-map-edit'));},generateAll:()=>{showProduction();$('hd-batch').click();},generateOne:openHD,production:showProduction,preview:openHD,holeSelect:n=>{imageEditor.close();if(sync())loadHole(n);}});
  const recognitionEntry=document.createElement('button');recognitionEntry.id='wholecourse-open';recognitionEntry.className='wide';recognitionEntry.textContent='整场归属分析 / 候选接入';document.querySelector('.workflow-tools').append(recognitionEntry);recognitionEntry.onclick=()=>{$('generation-options').open=true;document.querySelector('.recognition-tools').scrollIntoView({block:'start'});$('recognition-audit').focus();};
  let place=null, vector=false, watch=null, live=null, liveMarker=null, routePosition=null, catalog=[], saveTimer=null, restoring=false,imageTrace=null,modelRecognition=null;
  const status=t=>$('live-status').textContent=t;
  let exportURL=null;
  const dl=(name,data,type)=>{if(exportURL)URL.revokeObjectURL(exportURL);exportURL=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=exportURL;a.download=name;a.textContent='下载：'+name;const host=$('generation-export');if(host){host.replaceChildren(a);const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent='查看最近导出内容';const content=document.createElement('textarea');content.readOnly=true;content.setAttribute('aria-label','最近导出内容');content.value=data.length<2e6?data:'文件较大，请使用上方下载链接。';detail.append(summary,content);host.append(detail);}else document.body.append(a);a.click();if(!host)a.remove();};
  function sync(){if(!courseData||restoring||inOverview)return false;const ok=saveHole(true);refresh();return ok!==false;}
  async function closePhoto(){if(photo.hidden)return;photo.hidden=true;$('photo-frame').src='about:blank';courseData=await CourseStore.load(GB);loadHole(curHole);refresh();}
  function updateDistance(){
    const from=$('distance-from').value==='live'?live:$('distance-from').value==='route-live'?routePosition:catalog.find(p=>p.id===$('distance-from').value),to=catalog.find(p=>p.id===$('distance-to').value);
    if(!from||!to){$('distance-value').textContent='— m';$('distance-meta').textContent='请在图上放点，并选择有效起点和目标。';imageEditor.refresh();return;}
    $('distance-value').textContent=PW.distanceMeters(from.coordinate,to.coordinate).toFixed(1)+' m';
    $('distance-meta').textContent='两点间地表直线距离（不是沿车道距离）\n起点 '+from.coordinate.map(x=>x.toFixed(7)).join(', ')+'\n终点 '+to.coordinate.map(x=>x.toFixed(7)).join(', ')+'\n'+[CourseGNSS.describe(from),CourseGNSS.describe(to)].filter(Boolean).join('\n');
    $('point-lng').value=from.coordinate[0];$('point-lat').value=from.coordinate[1];
    imageEditor.refresh();
  }
  function refresh(){if(!courseData)return;catalog=PW.buildCatalog({...courseData,slug:GB}).points;
    $('project-name').value=courseData.name;$('project-audit').textContent='项目 '+GB+' · 保存版本 '+(courseData.revision||0)+'\n'+CourseProjects.audit(courseData).map(x=>'第 '+x.hole+' 洞：'+(x.geometry?'有 Tee / 果岭':'地理要素待补')+' · '+(x.image?'有图片':'未绑图片')+' · '+x.controls+' 个图片控制点').join('\n');
    legacy.hidden=!(courseData.legacy_editor==='holemap-viewer/index.html'&&courseData.source_project_id===GB);
    $('node-data').value=JSON.stringify(currentHoleData(),null,2);
    quickHole.replaceChildren(...courseData.holes.map(h=>new Option('第 '+h.n+' 洞',String(h.n))));quickHole.value=String(curHole);
    for(const id of ['distance-from','distance-to']){const s=$(id),old=s.value;s.replaceChildren();if(id==='distance-from'&&live)s.add(new Option('设备实时 GPS','live'));if(id==='distance-from'&&routePosition)s.add(new Option('本洞路线模拟球车','route-live'));for(const p of catalog)s.add(new Option('第 '+p.hole+' 洞 · '+p.name+(p.source==='derived_geometry'?'（几何推导）':''),p.id));if([...s.options].some(o=>o.value===old))s.value=old;else if(id==='distance-to'){const flag=catalog.find(p=>p.hole===curHole&&p.role==='flag');if(flag)s.value=flag.id;}}
    $('workspace-title').textContent=courseData.name+' · 第 '+curHole+' 洞';
    $('workspace-quality').textContent=(courseData.source_import?'原站 '+courseData.source_import.venue_id+' 的本机副本。':'')+(currentHoleData()?.green?.length?'本洞有地理要素；影像 / 配准精度待核验。':'本洞尚无果岭几何。可在实景图描点画线；未建立的范围不会虚构。')+(currentHoleData()?.par_status==='unknown'&&currentHoleData().par==null?' PAR 待核对。':'');
    updateDistance();styleScene();generation.refresh();production.refresh();workflow.refresh();
  }
  function styleScene(){if(vector&&!Object.values(TYPES).some(t=>t.g!=='marker'&&currentHoleData()?.[t.key]?.length)){vector=false;$('mode-real').setAttribute('aria-pressed','true');$('mode-vector').setAttribute('aria-pressed','false');}document.body.classList.toggle('vector-scene',vector);for(const l of map.pm.getGeomanLayers()){const s=TYPES[l._gtype];if(l.setStyle&&s?.fill)l.setStyle({fillOpacity:vector?0.93:0.45});}}
  function cancel(){imageTrace?.cancel();modelRecognition?.cancel();place=null;map.pm.disableDraw();map.getContainer().style.cursor='';status('已结束放点。可拖动已有标记，或使用左侧原版编辑工具。');}
  function arm(kind){cancel();place=kind;map.getContainer().style.cursor='crosshair';status(kind==='pin'?'点击地图设置当前洞果岭中旗。':'点击地图放置'+(kind==='cart_test'?'球车':'自定义目标')+'；放下后可直接拖动。');}
  function putPoint(kind,coord,name,id,meta={}){
    const h=currentHoleData();if(!h)return;const existing=(h.device_points||[]).find(p=>p.id===id);
    if(existing){existing.coordinate=coord;for(const k of ['accuracy_confidence','fix_type','correction_age_s','receiver'])delete existing[k];Object.assign(existing,{source:'manual_map',accuracy_m:null,updated_at:new Date().toISOString()},meta);}
    else{h.device_points??=[];h.device_points.push({id:id||crypto.randomUUID(),name:name||'自定义点',kind,coordinate:coord,source:'manual_map',accuracy_m:null,...meta});}
    CourseStore.save(GB,courseData);localStorage.setItem('golfmap.gps-draft.'+GB+'.hole-'+curHole,JSON.stringify({hole_data:h}));
    restoring=true;loadHole(curHole);restoring=false;refresh();
    const p=catalog.find(p=>p.local_id===(id||h.device_points.at(-1).id)&&p.hole===curHole);if(p)$('distance-from').value=p.id;updateDistance();
  }
  $('place-cart').onclick=()=>arm('cart_test');$('place-point').onclick=()=>arm('reference');$('place-pin').onclick=()=>arm('pin');$('cancel-tool').onclick=cancel;
  $('draw-route').onclick=()=>{cancel();curType='cartroute';map.pm.enableDraw('Line');status('沿真实球车道依次点击，点击最后一个节点完成；不会使用球道中线代替车道。');};
  map.on('click',e=>{if(!place)return;const kind=place;cancel();sync();const c=[e.latlng.lng,e.latlng.lat];if(kind==='pin'){const h=currentHoleData();h.pins={...h.pins,mid:c};h.flag=c;CourseStore.save(GB,courseData);localStorage.setItem('golfmap.gps-draft.'+GB+'.hole-'+curHole,JSON.stringify({hole_data:h}));loadHole(curHole);refresh();}else putPoint(kind,c,$('point-name').value.trim()||(kind==='cart_test'?'球车 '+((currentHoleData().device_points||[]).length+1):'自定义目标'));status('已放置并保存本机草稿。');});
  $('mode-real').onclick=async()=>{await closePhoto();vector=false;styleScene();$('mode-real').setAttribute('aria-pressed','true');$('mode-vector').setAttribute('aria-pressed','false');};
  $('mode-vector').onclick=async()=>{await closePhoto();const h=currentHoleData();if(!h||!Object.values(TYPES).some(t=>t.g!=='marker'&&h[t.key]?.length)){vector=false;styleScene();$('mode-real').setAttribute('aria-pressed','true');$('mode-vector').setAttribute('aria-pressed','false');generation.open();status('本洞还没有地图要素。请从左上“生成虚拟图与 GPS 数据”读取地图或在实景上绘制；暂保留卫星图。');return;}vector=true;styleScene();$('mode-real').setAttribute('aria-pressed','false');$('mode-vector').setAttribute('aria-pressed','true');zoomToHole();};
  $('mode-gps').onclick=async()=>{await closePhoto();reveal(panel);sync();};
  $('mode-hd').textContent='高清虚拟图';$('mode-hd').onclick=openHD;
  $('mode-real').textContent='卫星地图';$('mode-vector').textContent='轮廓编辑';$('workspace-save').textContent='保存';
  for(const id of ['mode-real','mode-vector','mode-gps']){const handler=$(id).onclick;$(id).onclick=async()=>{imageTrace?.cancel();modelRecognition?.cancel();imageEditor.close();mapPick=null;await handler();};}
  const previousHoleChange=quickHole.onchange;quickHole.onchange=()=>{const wasHD=!imagePanel.hidden;imageEditor.close();mapPick=null;previousHoleChange();if(wasHD)openHD();else selectView(vector?'mode-vector':'mode-real');};
  $('project-rename').onclick=()=>{try{const name=$('project-name').value.trim();if(!name)throw Error('项目名称不能为空');if(!sync())return;courseData.name=name;CourseStore.register(GB,courseData);refresh();toast('项目名称已保存');}catch(e){status(e.message);}};
  $('project-pack').onclick=async()=>{const b=$('project-pack');try{if(!sync())return;b.disabled=true;status('正在将球洞数据、图片与配准整理为可携带项目包…');const pack=await CourseProjects.exportPack(courseData),text=JSON.stringify(pack);$('project-pack-preview').value=text.length<2e6?text:'项目包较大，请直接使用下载文件导入。';dl(GB+'.golf-project.json',text,'application/json');status('完整项目包已下载；换浏览器后可从地图页导入。');}catch(e){status('项目包未生成：'+e.message);}finally{b.disabled=false;}};
  $('photo-close').onclick=closePhoto;
  $('workspace-save').onclick=()=>{if(sync())toast('已保存本机球场数据；刷新可恢复。',true);};
  $('distance-from').onchange=updateDistance;$('distance-to').onchange=updateDistance;
  $('apply-coordinate').onclick=()=>{const coord=[$('point-lng').value,$('point-lat').value].map(x=>x.trim()===''?NaN:Number(x));if(!CourseStore.valid(coord)){status('坐标无效，请填写 WGS84 经度和纬度。');return;}const p=catalog.find(p=>p.id===$('distance-from').value);if(!p||p.hole!==curHole){status('请先选择本洞的一个球车或自定义点作为起点。');return;}const h=currentHoleData(),d=h.device_points?.find(x=>x.id===p.local_id);if(!d){status('此处更新球车 / 自定义点；Tee 和果岭请直接拖动或使用原版工具。');return;}sync();putPoint(d.kind,coord,d.name,d.id,{source:'manual_coordinate',accuracy_m:null});status('所选点坐标已更新并保存。');};
  let lastFix=null;
  function gnssOptions(){const maxAccuracy=Number($('gnss-limit').value);if(!Number.isFinite(maxAccuracy)||maxAccuracy<0.01||maxAccuracy>100)throw Error('水平误差门槛需在 0.01–100 m 之间');return {maxAccuracy};}
  function clearLive(){live=null;if(liveMarker)map.removeLayer(liveMarker);liveMarker=null;}
  function rejectLive(message){clearLive();status(message+'；未将不合格点当作当前 GPS。');refresh();$('distance-from').value='';updateDistance();}
  $('live-start').onclick=()=>{if(watch!==null)return;if(!navigator.geolocation){status('此浏览器不支持定位。');return;}try{gnssOptions();}catch(e){status(e.message);return;}$('cartstop').click();lastFix=null;watch=navigator.geolocation.watchPosition(pos=>{try{const sample=CourseGNSS.browserSample(pos),q=CourseGNSS.evaluate(sample,lastFix,gnssOptions());if(!q.accepted){rejectLive(q.message);return;}lastFix=sample;live=sample;const ll=C2L(live.coordinate);if(!liveMarker)liveMarker=L.circleMarker(ll,{radius:9,color:'#fff',fillColor:'#128bfa',fillOpacity:1,pmIgnore:true}).addTo(map).bindTooltip('设备实时 GPS');else liveMarker.setLatLng(ll);status(CourseGNSS.describe(live)+'；范围：'+PW.rangeStatus(live.coordinate,currentHoleData()));refresh();$('distance-from').value='live';updateDistance();}catch(e){rejectLive(e.message);}},err=>{rejectLive('定位失败：'+err.message);},{enableHighAccuracy:true,maximumAge:0,timeout:15000});status('正在申请定位；等待符合精度门槛的新位置…');imageEditor.refresh();};
  const freshnessTimer=setInterval(()=>{if(live&&Date.now()-Date.parse(live.updated_at)>CourseGNSS.defaults.maxAge)rejectLive('定位已超过 10 秒未更新');else imageEditor.updateQuality();},1000);
  window.addEventListener('pagehide',()=>clearInterval(freshnessTimer));
  $('gnss-apply').onclick=()=>{try{const rows=CourseGNSS.snapshot($('gnss-input').value,currentHoleData().device_points||[],gnssOptions()),bad=rows.filter(x=>!x.quality.accepted);if(bad.length)throw Error(bad.map(x=>x.sample.id+'：'+x.quality.message).join('；'));if(!sync())throw Error('当前项目保存失败');const h=currentHoleData(),next=structuredClone(h.device_points||[]);for(const {sample} of rows){const i=next.findIndex(x=>x.id===sample.id);if(i>=0)next[i]={...next[i],...sample};else next.push(sample);}const old=h.device_points;h.device_points=next;try{persistImageChange();}catch(e){h.device_points=old;throw e;}$('gnss-status').textContent='已接入 '+rows.length+' 个设备快照，保存原始坐标及精度声明；这是快照，不是持续连接。';}catch(e){$('gnss-status').textContent='未接入：'+e.message;}};
  $('live-stop').onclick=()=>{if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;live=null;if(liveMarker)map.removeLayer(liveMarker);liveMarker=null;refresh();};window.addEventListener('pagehide',()=>$('live-stop').click());
  $('apply-telemetry').onclick=()=>{try{const text=$('telemetry').value;const r=PW.parseTelemetry(text,text.trim().startsWith('{')||text.trim().startsWith('[')?'json':'csv');if(r.errors.length)throw Error(r.errors.map(x=>x.message).join('；'));sync();for(const p of r.positions)putPoint('cart_test',p.coordinate,p.name||p.id,p.id,{source:'gps_import',accuracy_m:p.accuracy_m,updated_at:p.updated_at});status('已更新 '+r.positions.length+' 个设备点位。');}catch(e){status(e.message);}};
  $('export-points').onclick=()=>{sync();dl(GB+'-points.geojson',JSON.stringify(PW.exportGeoJSON({...courseData,slug:GB}),null,2),'application/geo+json');};
  $('export-vector').onclick=()=>{
    sync();const h=currentHoleData(),layers=map.pm.getGeomanLayers().filter(l=>l._gtype&&l.getLatLngs);if(!layers.length){status('本洞没有线或面几何，不能生成虚假的球洞图。请先建立地理要素。');return;}
    const bounds=L.featureGroup(layers).getBounds().pad(.12),nw=map.options.crs.project(bounds.getNorthWest()),se=map.options.crs.project(bounds.getSouthEast()),width=1000,height=Math.round(1000*(nw.y-se.y)/(se.x-nw.x));
    const project=ll=>{const p=map.options.crs.project(ll);return [(p.x-nw.x)/(se.x-nw.x)*width,(nw.y-p.y)/(nw.y-se.y)*height];};
    const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
    const shapes=layers.map(l=>{let points=l.getLatLngs();if(Array.isArray(points[0]))points=points[0];const t=TYPES[l._gtype],poly=l instanceof L.Polygon;return '<'+(poly?'polygon':'polyline')+' points="'+points.map(p=>project(p).join(',')).join(' ')+'" fill="'+(poly?(t?.fill||'none'):'none')+'" stroke="'+(t?.color||'#f5c36b')+'" stroke-width="3"/>';}).join('');
    const pts=catalog.filter(p=>p.hole===curHole).map(p=>{const [x,y]=project(L.latLng(C2L(p.coordinate)));return '<circle cx="'+x+'" cy="'+y+'" r="5" fill="#fff"/><text x="'+(x+8)+'" y="'+y+'" fill="#fff" font-size="12">'+esc(p.name)+'</text>';}).join('');
    const metadata={coordinate_system:'WGS84',render_projection:'EPSG:3857',bounds:[[bounds.getWest(),bounds.getSouth()],[bounds.getEast(),bounds.getNorth()]],accuracy_m:null,hole:h,map_source:courseData.map_generation?.source};
    const attribution=courseData.map_generation?'<text x="12" y="'+(height-12)+'" fill="#fff" font-size="12">© OpenStreetMap contributors · ODbL · 地图草稿，未实测</text>':'';
    dl(GB+'-hole-'+curHole+'.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+width+' '+height+'"><metadata>'+esc(JSON.stringify(metadata))+'</metadata><rect width="100%" height="100%" fill="#253c22"/>'+shapes+pts+attribution+'</svg>','image/svg+xml');status('已生成坐标驱动的矢量虚拟图，包含原始地理数据与投影范围。');
  };
  function hookLayers(){if(cartMarker){routePosition={coordinate:L2C(cartMarker.getLatLng())};if(!cartMarker._workspaceHooked){cartMarker._workspaceHooked=true;cartMarker.on('move',()=>{routePosition={coordinate:L2C(cartMarker.getLatLng())};if($('distance-from').value==='route-live')updateDistance();});}}else routePosition=null;for(const l of map.pm.getGeomanLayers()){if(l._workspaceHooked)continue;l._workspaceHooked=true;l.on('dragend pm:edit pm:dragend',()=>{clearTimeout(saveTimer);saveTimer=setTimeout(sync,100);});}}
  window.addEventListener('hole-loaded',()=>{const url=new URL(location.href);url.searchParams.set('hole',String(curHole));history.replaceState(null,'',url);cancel();hookLayers();refresh();if(!restoring)zoomToHole();});window.addEventListener('course-loaded',()=>{zoomToHole();hookLayers();refresh();});
  map.on('pm:create pm:remove',()=>{hookLayers();clearTimeout(saveTimer);saveTimer=setTimeout(sync,100);});
  // Existing source controls remain available; map state is never CSS-scaled.
  imageTrace=createImageTraceUI($('side'),{map,course:()=>courseData,hole:()=>currentHoleData(),provider:()=>curSrc,layer:()=>baseLayers[curSrc],sync,begin:async()=>{cancel();armSE=null;stopCart(false);if(!sync())throw Error('请先处理当前保存错误');imageEditor.close();mapPick=null;await $('mode-real').onclick();},apply:async c=>{CourseStore.validate(c);CourseStore.save(GB,c);for(const h of c.holes)localStorage.setItem('golfmap.gps-draft.'+GB+'.hole-'+h.n,JSON.stringify({hole_data:h}));courseData=c;restoring=true;loadHole(curHole);restoring=false;refresh();}});
  const modelOptions=document.createElement('details');modelOptions.id='model-options';modelOptions.innerHTML='<summary>AI 卫星识别（试验功能，结果需核对）</summary>';document.querySelector('.workflow-tools').after(modelOptions);
  modelRecognition=createModelRecognitionUI(modelOptions,{map,course:()=>courseData,hole:()=>currentHoleData(),provider:()=>curSrc,layer:()=>baseLayers[curSrc],begin:async()=>{cancel();armSE=null;stopCart(false);if(!sync())throw Error('请先处理保存错误');imageEditor.close();mapPick=null;await $('mode-real').onclick();},review:data=>generation.importCandidates(data)});
  const modelEntry=document.createElement('button');modelEntry.className='wide';modelEntry.textContent='AI 卫星识别（本机试验版）';document.querySelector('.workflow-tools').append(modelEntry);modelEntry.onclick=()=>{modelOptions.open=true;modelOptions.scrollIntoView({block:'start'});$('model-start').focus();};
  const traceDetails=fold('.trace-tools','trace-options','从卫星影像辅助提取轮廓（试验功能）');
  const traceShortcut=document.createElement('button');traceShortcut.id='generation-trace';traceShortcut.textContent='试用卫星影像辅助提取';traceShortcut.className='wide';$('generate-draw').before(traceShortcut);traceShortcut.onclick=()=>{generation.close();traceDetails.open=true;traceDetails.scrollIntoView({block:'start'});};
  const traceEmpty=document.createElement('button');traceEmpty.textContent='试用卫星影像辅助提取';traceEmpty.className='wide';document.getElementById('generation-help').append(traceEmpty);traceEmpty.onclick=traceShortcut.onclick;
  // A small daily-use surface; retain every legacy tool under explicit disclosure.
  const pointDetails=document.createElement('details');pointDetails.id='simple-points';pointDetails.className='workflow-advanced';pointDetails.innerHTML='<summary>地图放点 / GPS</summary>';panel.before(pointDetails);pointDetails.append(panel);
  const editDetails=document.createElement('details');editDetails.id='simple-map-edit';editDetails.className='workflow-advanced';editDetails.innerHTML='<summary>地图点线面编辑</summary>';for(const el of originalSideNodes)editDetails.append(el);
  const advanced=document.createElement('details');advanced.id='simple-advanced';advanced.className='workflow-advanced';advanced.innerHTML='<summary>更多工具</summary>';const workflowBox=document.querySelector('.workflow-tools');for(const el of [...$('side').children])if(el!==workflowBox&&el!==$('simple-points'))advanced.append(el);
  advanced.prepend(copy,$('mode-vector'),$('mode-gps'));advanced.append(recognitionEntry,modelEntry);
  $('side').replaceChildren(workflowBox,$('simple-points'),editDetails,advanced);
  for(const b of [recognitionEntry,modelEntry,traceShortcut,traceEmpty]){const handler=b.onclick;b.onclick=()=>{advanced.open=true;handler();};}
  const recognitionHandler=recognitionEntry.onclick;recognitionEntry.onclick=()=>{advanced.open=true;recognitionHandler();};
  bar.insertBefore($('mode-hd'),$('mode-real'));$('hd-open').onclick=openHD;
  for(const id of ['mode-real','mode-vector']){const handler=$(id).onclick;$(id).onclick=async()=>{await handler();selectView(vector?'mode-vector':'mode-real');};}
  setVirtualDock(false);setSrc('esri');map.invalidateSize();if(courseData){hookLayers();refresh();zoomToHole();}
})();
