/* Reusable generation and survey QA entry point, always local to the selected project. */
function createProductionUI(host,api){
  const box=document.createElement('section');box.className='workspace-tools production-tools';
  box.innerHTML=`<h2>高清虚拟图 · 实地精度</h2><p>按本洞已有地图几何制图，生成后直接放点 / GPS 测距。不是 AI 猜测地形，也不是卫星照片。</p>
  <label>高清尺寸<select id="hd-size"><option value="2048">2K · 2048 px</option><option value="3072" selected>3K · 3072 px</option><option value="4096">4K · 4096 px</option></select></label>
  <button id="hd-generate" class="wide">生成本洞高清虚拟图</button><button id="hd-batch" class="wide">为全场缺图球洞批量生成</button><button id="hd-open" class="wide">打开高清图 · 放点 / GPS</button>
  <details><summary>已有图片与版本</summary><label><input id="hd-replace" type="checkbox">允许替换本洞已有图（保留上一版）</label><button id="hd-restore">恢复上一版图片</button><button id="hd-download">下载当前 PNG / 图片</button></details><p id="hd-status" role="status"></p>
  <details id="field-panel"><summary>实测精度检查 / 校准依据</summary><p>地图点与现场同一地物配对。control 用于估算偏移，check 必须是未参与校准的独立检查点。至少 3 个分散检查点。容差和仪器精度需自行确定，本工具不出具测绘认证。</p>
  <label>本洞地图对应点<select id="field-map-point"></select></label><label>现场实测经度<input id="field-lng" type="number" step="any"></label><label>现场实测纬度<input id="field-lat" type="number" step="any"></label><label>用途<select id="field-role"><option value="check">独立检查点</option><option value="control">校准控制点（不参与验收）</option></select></label><label>测量来源<select id="field-source"><option value="rtk">RTK</option><option value="survey">测绘成果</option><option value="gnss">普通 GNSS</option></select></label><label>仪器 / 成果名称<input id="field-instrument"></label><label>声明参考精度（m）<input id="field-accuracy" type="number" step="any" min="0"></label><label>实际采集时间<input id="field-time" type="datetime-local"></label><label>检查容差（m）<input id="field-threshold" type="number" step="any" value="2" min="0"></label><button id="field-add">加入实测对应点</button>
  <label>或导入实测文件 JSON<input id="field-file" type="file" accept="application/json,.json"></label><textarea id="field-input" aria-label="实测精度数据" placeholder='{"coordinate_system":"WGS84","threshold_m":2,"points":[]}'></textarea><button id="field-template">下载空白录入模板</button><button id="field-check">检查并保存报告</button><button id="field-report">下载本洞精度报告</button><p id="field-status" role="status">未提供实测点，不能确认实际精度。</p><pre id="field-result"></pre></details>`;
  host.prepend(box);const $=id=>box.querySelector('#'+id);let busy=false,url=null;
  function download(name,blob){if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.textContent='下载 '+name;const old=box.querySelector('.production-download');old?.remove();a.className='production-download';box.append(a);a.click();}
  const saveJSON=(name,data)=>download(name,new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));
  const textReport=r=>r?`${({insufficient_independent_coverage:'独立检查点数量 / 分布不足',reference_accuracy_insufficient:'参考仪器精度不足',submitted_checks_within_tolerance:'所提交检查点在容差内（非全场认证）',submitted_checks_exceed_tolerance:'所提交检查点超出容差'})[r.status]}\n独立检查 ${r.independent_count} 点 · RMS ${r.rms_m?.toFixed(2)??'—'} m · 最大 ${r.max_m?.toFixed(2)??'—'} m\n${r.warning}`:'未提供实测点，不能确认实际精度。';
  let fieldHole=null;
  const currentPoints=()=>HolePointWorkspace.buildCatalog(api.course()).points.filter(p=>p.hole===api.hole().n);
  function refresh(){const h=api.hole();if(!h)return;const v=h.visual,stale=v?.generator&&!CourseHD.current(v,h);if(!busy)$('hd-status').textContent=v?(stale?'地理要素已改变，请重新生成图片；点位仍使用当前坐标。':`第 ${h.n} 洞已有 ${v.width} × ${v.height} 图片 · ${v.generator?'坐标自动配准（非实测）':'配准状态请打开图片检查'}`):`第 ${h.n} 洞未生成高清图。`; $('hd-restore').disabled=!h.visual_previous;$('field-status').textContent=textReport(h.field_audit?.report);
    const select=$('field-map-point'),old=select.value;select.replaceChildren(...currentPoints().map(p=>new Option(p.name,p.id)));if([...select.options].some(o=>o.value===old))select.value=old;
    if(fieldHole!==h.n){fieldHole=h.n;$('field-input').value=h.field_audit?JSON.stringify(h.field_audit.input,null,2):'';$('field-result').textContent='';for(const id of ['field-lng','field-lat','field-time'])$(id).value='';}
  }
  async function generate(batch){if(busy||!api.sync())return false;const c=api.course(),hole=api.hole(),targets=batch?c.holes.filter(h=>!h.visual):[hole];if(!batch&&hole.visual&&!$('hd-replace').checked){$('hd-status').textContent='本洞已有图片。如需重绘，先在“已有图片与版本”勾选允许替换；不会自动覆盖。';return false;}
    busy=true;$('hd-generate').disabled=$('hd-batch').disabled=true;let done=0,skipped=[];
    try{for(const h of targets){$('hd-status').textContent=`正在生成第 ${h.n} 洞…`;await new Promise(r=>setTimeout(r,0));try{const result=await CourseHD.render(h,c.name,+$('hd-size').value);result.visual.asset_id=await CourseProjects.put(result.blob);if(h.visual)h.visual_previous=structuredClone(h.visual);h.visual=result.visual;api.save(c);done++;}catch(e){skipped.push('第 '+h.n+' 洞：'+e.message);}}
      $('hd-status').textContent=`已生成 ${done} 洞；${skipped.length} 洞未生成。${skipped.join('；')}${!targets.length?'所有球洞已有图片，未覆盖。':''} 图片是坐标驱动制图；无实测数据仍不能确认现场精度。`;
    }catch(e){$('hd-status').textContent='生成未完成：'+e.message;}finally{const result=$('hd-status').textContent;busy=false;$('hd-generate').disabled=$('hd-batch').disabled=false;$('hd-replace').checked=false;api.refresh();$('hd-status').textContent=result;}
    return done>0&&skipped.length===0&&api.course()===c&&api.hole()===hole;
  }
  $('hd-generate').onclick=()=>generate(false);$('hd-batch').onclick=()=>generate(true);$('hd-open').onclick=api.open;
  $('hd-restore').onclick=()=>{if(!api.sync())return;const h=api.hole();if(!h.visual_previous)return;[h.visual,h.visual_previous]=[h.visual_previous,h.visual];api.save(api.course());refresh();};
  $('hd-download').onclick=async()=>{try{const v=api.hole().visual;if(!v)throw Error('请先生成或绑定本洞图片');const b=await CourseProjects.source(v);download('hole-'+api.hole().n+'.'+(({ 'image/jpeg':'jpg','image/webp':'webp'})[b.type]||'png'),b);}catch(e){$('hd-status').textContent=e.message;}};
  $('field-template').onclick=()=>saveJSON('field-observations-template.json',{coordinate_system:'WGS84',threshold_m:2,points:[],instructions:'每点填写 {id,role:"control" 或 "check",map:[经度,纬度],measured:[实测经度,实测纬度],source:"rtk" 或 "survey" 或 "gnss",instrument:"仪器名称",accuracy_m:参考精度米,observed_at:"ISO采集时间"}。不预填示例坐标以免误用。'});
  $('field-add').onclick=()=>{try{const p=currentPoints().find(p=>p.id===$('field-map-point').value);if(!p)throw Error('先在地图建立本洞对应点');const vals=['field-lng','field-lat','field-accuracy','field-threshold','field-time'].map(id=>$(id).value);if(vals.some(v=>!v.trim()))throw Error('请填写实测坐标、精度、容差和实际采集时间');const input=$('field-input').value.trim()?JSON.parse($('field-input').value):{coordinate_system:'WGS84',points:[]};input.threshold_m=+vals[3];input.points.push({id:p.id,map:p.coordinate.slice(),measured:[+vals[0],+vals[1]],role:$('field-role').value,source:$('field-source').value,instrument:$('field-instrument').value.trim(),accuracy_m:+vals[2],observed_at:new Date(vals[4]).toISOString()});CourseFieldAudit.audit(input);$('field-input').value=JSON.stringify(input,null,2);$('field-status').textContent='已加入 '+input.points.length+' 个对应点，点击“检查并保存报告”。';}catch(e){$('field-status').textContent='未加入：'+e.message;}};
  $('field-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1e6)throw Error('文件超过 1 MB');const data=JSON.parse(await f.text());$('field-input').value=JSON.stringify(data,null,2);$('field-status').textContent='已载入，点击检查；尚未写入项目。';}catch(e){$('field-status').textContent=e.message;}};
  $('field-check').onclick=()=>{try{if(!api.sync())return;const input=JSON.parse($('field-input').value),report=CourseFieldAudit.audit(input);api.hole().field_audit={input,report,checked_at:new Date().toISOString()};api.save(api.course());$('field-status').textContent=textReport(report);$('field-result').textContent=JSON.stringify(report,null,2);}catch(e){$('field-status').textContent='未保存：'+e.message;}};
  $('field-report').onclick=()=>{const a=api.hole().field_audit;if(!a){$('field-status').textContent='没有本洞报告，请先输入现场数据。';return;}saveJSON('hole-'+api.hole().n+'-field-audit.json',a);};
  return {refresh,generate,isBusy:()=>busy};
}
