/* Portable projects: all images are local IndexedDB blobs or bundled reference assets. */
(function(root,factory){const api=factory(typeof module==='object'?require('./store.js'):root.CourseStore);if(typeof module==='object')module.exports=api;else root.CourseProjects=api;})(typeof globalThis!=='undefined'?globalThis:this,function(S){
  'use strict';const FORMAT='golf-project/1',MAX_ASSET=20*1024*1024,MAX_PACKAGE=256*1024*1024;
  const clone=x=>JSON.parse(JSON.stringify(x));
  const visuals=course=>course.holes.flatMap(h=>[h.visual,h.visual_previous].filter(Boolean));
  const imageData=s=>typeof s==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(s)&&s.length<=MAX_ASSET*1.4;
  function validate(pack){if(!pack||pack.format!==FORMAT)throw Error('不支持的项目包版本');S.validate(pack.course);if(!pack.assets||typeof pack.assets!=='object'||Array.isArray(pack.assets))throw Error('项目图片字典缺失');for(const [id,a] of Object.entries(pack.assets)){if(!/^[a-zA-Z0-9_-]{1,100}$/.test(id)||!imageData(a.data))throw Error('无效图片，仅支持 PNG/JPEG/WebP');}
    for(const v of visuals(pack.course)){if(!Number.isFinite(v.width)||!Number.isFinite(v.height)||v.width<1||v.height<1||v.width*v.height>50000000)throw Error('图片尺寸无效');if(!v.asset_id||!pack.assets[v.asset_id])throw Error('项目包缺少当前或上一版图片');if(v.controls&&!Array.isArray(v.controls))throw Error('配准点格式错误');for(const p of [...(v.controls||[]),...(v.checkpoints||[])])if(!S.valid(p.coordinate)||!Number.isFinite(p.pixel?.x)||!Number.isFinite(p.pixel?.y)||p.pixel.x<0||p.pixel.y<0||p.pixel.x>v.width||p.pixel.y>v.height)throw Error('配准点无效或超出图片');}return pack;}
  let database;function db(){return database??=new Promise((resolve,reject)=>{const r=indexedDB.open('golf-project-assets',1);r.onupgradeneeded=()=>r.result.createObjectStore('images');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('无法打开图片存储，请导出备份并检查浏览器权限'));});}
  async function transaction(mode,fn){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction('images',mode);let value;const r=fn(t.objectStore('images'));r.onsuccess=()=>value=r.result;t.oncomplete=()=>resolve(value);t.onerror=t.onabort=()=>reject(Error('图片保存失败或空间不足'));});}
  const get=id=>transaction('readonly',s=>s.get(id));
  async function put(blob){if(!['image/png','image/jpeg','image/webp'].includes(blob.type)||blob.size>MAX_ASSET)throw Error('请选择不超过 20 MB 的 PNG/JPEG/WebP 图片');const bytes=await blob.arrayBuffer(),id='image-'+Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');await transaction('readwrite',s=>s.put(blob,id));return id;}
  async function source(v){if(v.asset_id){const b=await get(v.asset_id);if(!b)throw Error('本机缺少图片，请重新导入完整项目包');return b;}if(!/^(holemap-hd|kingswan)\/assets\/[a-zA-Z0-9_.-]+\.(png|jpg|jpeg|webp)$/.test(v.src||''))throw Error('图片来源无效；请上传本地图片');const r=await fetch('../'+v.src);if(!r.ok)throw Error('图片读取失败');return r.blob();}
  const dataURL=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});
  async function exportPack(course){const c=clone(course),assets={};let total=0;for(const v of visuals(c)){const b=await source(v);total+=b.size*1.4;if(total>MAX_PACKAGE)throw Error('项目图片过大，请先压缩图片');const id=await put(b);assets[id]??={data:await dataURL(b)};v.asset_id=id;delete v.src;}delete c.legacy_editor;return validate({format:FORMAT,exported_at:new Date().toISOString(),field_verified:false,course:c,assets});}
  async function importPack(input){const pack=validate(clone(input));const ids=new Map();for(const [id,a] of Object.entries(pack.assets)){const b=await (await fetch(a.data)).blob(),bitmap=await createImageBitmap(b);try{if(bitmap.width*bitmap.height>50000000)throw Error('图片尺寸过大');for(const v of visuals(pack.course))if(v.asset_id===id&&(v.width!==bitmap.width||v.height!==bitmap.height))throw Error('图片实际尺寸与项目记录不一致');}finally{bitmap.close();}ids.set(id,await put(b));}const c=pack.course;for(const v of visuals(c)){v.asset_id=ids.get(v.asset_id);delete v.src;delete v.model;}const id='local-'+crypto.randomUUID();c.source_project_id??=c.project_id||c.slug;c.name+=' · 导入';S.register(id,c);return id;}
  function fromGeoJSON(fc){if(fc.type!=='FeatureCollection'||!Array.isArray(fc.features)||!fc.features.length)throw Error('需要非空 FeatureCollection');if(fc.coordinate_system&&!['WGS84','WGS84 / EPSG:4326','EPSG:4326'].includes(fc.coordinate_system)||fc.crs)throw Error('只接受 WGS84 / EPSG:4326，拒绝隐含坐标系转换');const holes=new Map(),coords=[],sourceFeatures=[];
    const polygons={hole_perimeter:['holeperim',false],green:['green',false],tee_box:['teebox',false],fairway:['fairway',false],green_fringe:['fringe',true],rough:['rough',true],bunker:['bunkers',true],water:['water',true],bridge:['bridges',true]};
    const lines={centerline:['centerline',false],cart_drive_route:['cart_route',false],cart_path:['cartpaths',true],path:['paths',true],creek:['creeks',true],ditch:['ditches',true],out_of_bounds:['obs',true],fence:['fences',true],penalty_area_red:['hazards',true],penalty_area_yellow:['hazards_y',true]};
    for(const f of fc.features){const p=f.properties||{},n=Number(p.hole),g=f.geometry,t=p.feature_type||p.type;const check=v=>{if(Array.isArray(v)&&typeof v[0]==='number'){if(!S.valid(v))throw Error('GeoJSON 坐标无效');coords.push(v);}else if(Array.isArray(v)&&v.length)v.forEach(check);else throw Error('GeoJSON 几何为空或无效');};if(!g)throw Error('GeoJSON 缺少 geometry');check(g.coordinates);
      if(!Number.isInteger(n)||n<1||n>72)throw Error('每个要素需要 properties.hole (1–72)');if(!holes.has(n)){const h=S.blank('GeoJSON',[0,0],1).holes[0];h.n=n;holes.set(n,h);}const h=holes.get(n);
      if(g.type==='Polygon'&&polygons[t]){if(g.coordinates.length!==1||g.coordinates[0].length<4)throw Error('暂不支持内环或不足四节点的面；请保留原 GIS 文件');const [key,multi]=polygons[t],ring=g.coordinates[0];if(multi)(h[key]??=[]).push(ring);else{if(h[key]?.length)throw Error('同洞同类单面重复，需先在 GIS 合并');h[key]=ring;}}
      else if(g.type==='LineString'&&lines[t]){if(g.coordinates.length<2)throw Error('线至少两个节点');const [key,multi]=lines[t];if(multi)(h[key]??=[]).push(g.coordinates);else{if(h[key]?.length)throw Error('同洞同类主线重复');h[key]=g.coordinates;}}
      else if(g.type==='Point'){if(t==='tee'){if(!['black','gold','blue','white','red'].includes(p.color)||h.tees[p.color])throw Error('Tee 颜色无效或重复');h.tees[p.color]=g.coordinates;if(p.distance_m!=null)h.dist[p.color]=p.distance_m;}else if(t==='flag'||p.role==='flag'){h.flag=g.coordinates;h.pins.mid=g.coordinates;}else if(t==='tree')(h.trees??=[]).push(g.coordinates);else h.device_points.push({id:String(p.point_id||p.local_id||f.id||'point-'+h.device_points.length),name:p.name||t||'导入点',kind:p.kind==='cart'?'cart':'reference',coordinate:g.coordinates,source:p.source||'geojson_import',accuracy_m:p.accuracy_m??null});}
      else throw Error('未支持的几何 / 类型：'+g.type+' / '+t+'；不静默丢弃要素');sourceFeatures.push(f);
    }const c={name:fc.properties?.course_name||fc.name||'导入 GIS 球场',center:[coords.reduce((s,p)=>s+p[0],0)/coords.length,coords.reduce((s,p)=>s+p[1],0)/coords.length],coordinate_system:'WGS84',holes:[...holes.values()].sort((a,b)=>a.n-b.n),source_geojson:clone(fc),accuracy_m:null};return S.validate(c);}
  async function hydratePack(input){const pack=validate(clone(input)),ids=new Map();for(const [id,a] of Object.entries(pack.assets)){const b=await(await fetch(a.data)).blob(),bitmap=await createImageBitmap(b);try{for(const v of visuals(pack.course))if(v.asset_id===id&&(v.width!==bitmap.width||v.height!==bitmap.height))throw Error('后台图片尺寸不匹配');}finally{bitmap.close();}ids.set(id,await put(b));}for(const v of visuals(pack.course)){v.asset_id=ids.get(v.asset_id);delete v.src;delete v.model;}return pack.course;}
  function audit(c){return c.holes.map(h=>({hole:h.n,geometry:!!(h.green?.length&&Object.keys(h.tees||{}).length),image:!!h.visual,controls:h.visual?.controls?.length||0,field_verified:false}));}
  return {FORMAT,MAX_ASSET,MAX_PACKAGE,validate,imageData,source,get,put,exportPack,importPack,hydratePack,audit,fromGeoJSON};
});
