function createWorkflowUI(host,api){
  const W=CourseWorkflow,box=document.createElement('section');box.className='workspace-tools workflow-tools';
  box.innerHTML=`<h2>本洞制作</h2><p>先看高清图，再放点测距。缺少的地物在地图上补充。</p><button id="flow-next" class="wide"></button><p id="flow-progress" role="status"></p><div class="workflow-secondary"><button id="flow-edit">编辑地图</button><button id="flow-delivery">下载项目</button></div><details><summary>生成与检查</summary><button id="flow-source" class="wide">读取地图数据</button><button id="flow-generate" class="wide">生成全场缺图</button><button id="flow-preview" class="wide">打开本洞图片</button><button id="flow-settings" class="wide">画质 / 更新已有图</button><div id="flow-holes"></div></details><p class="workflow-note">保存到本机浏览器 · 实地精度待核验</p>`;
  host.prepend(box);const $=id=>document.getElementById(id);let busy=false,urls=[],reviewSnapshot=null;
  const drawer=document.createElement('section');drawer.className='generation-review';drawer.hidden=true;drawer.innerHTML=`<header><strong>交付前检查 · 本机项目包</strong><button id="flow-close">关闭检查</button></header><p>不会覆盖原站或 GitHub。本次下载包含所有当前 / 上一版图片、点线面、球车测试位置、实测记录及扩展字段；请先检查是否包含不宜分享的数据。</p><pre id="flow-report"></pre><label><input id="flow-confirm" type="checkbox">我已核对缺失项及点位隐私，以未实测草稿交付</label><button id="flow-export">下载完整项目包 + 检查报告</button><p id="flow-export-state" role="status"></p><div id="flow-links"></div>`;document.body.append(drawer);
  function refresh(){if(!api.course())return;const c=api.course(),s=W.assess(c),h=s.holes.find(h=>h.n===api.hole()?.n);$('flow-progress').textContent=`${s.total} 洞 · 可制图 ${s.renderable} · 已有图片 ${s.images} · 图与配准可供检查 ${s.ready}。实地精度未认证。`;
    $('flow-next').textContent=!h?.renderable?'补充本洞地图':!h.image?'生成高清图并打开':!h.registered?'打开图片 · 校准坐标':h.stale?'更新高清图':'打开高清图';
    $('flow-next').onclick=()=>{if(!h?.renderable)api.source();else if(!h.image)api.generateOne();else if(h.stale)api.production();else api.preview();};
    $('flow-holes').replaceChildren(...s.holes.map(row=>{const b=document.createElement('button');b.className='wide';b.textContent=`第 ${row.n} 洞 · ${({missing_geometry:'待建地理要素',needs_image:'待生成图',needs_registration:'待配准',needs_regeneration:'图片需更新',ready_for_review:'可编辑检查'})[row.stage]}\n缺少：${row.missing.join('、')||'未发现清单项缺失（仍需现场核验）'}`;b.onclick=()=>api.holeSelect(row.n);return b;}));
  }
  $('flow-source').onclick=api.source;$('flow-generate').onclick=api.generateAll;$('flow-preview').onclick=api.preview;$('flow-edit').onclick=api.edit;$('flow-settings').onclick=api.production;
  const key=()=> 'golfmap.delivery-review.'+(api.course().project_id||api.course().slug);
  function previous(){try{return JSON.parse(localStorage.getItem(key())||'null');}catch(_){return null;}}
  $('flow-delivery').onclick=async()=>{if(busy||!api.sync())return;drawer.hidden=false;$('flow-confirm').checked=false;$('flow-export').disabled=true;$('flow-export-state').textContent='正在检查…';try{reviewSnapshot=await W.snapshot(api.course());const changes=W.changes(reviewSnapshot,previous()),s=W.assess(api.course()),numbers=a=>a.length?a.join('、'):'无';$('flow-report').textContent=[api.course().name,'本机未实测草稿 · 未上传 / 未发布','',`新增洞：${numbers(changes.added)}`,`修改洞：${numbers(changes.changed)}`,`移除洞：${numbers(changes.removed)}`,`未变化：${changes.unchanged.length} 洞`,changes.metadata_changed?'球场基本信息有变化':'','',...s.holes.map(h=>`第 ${h.n} 洞：图片${h.image?'已绑定':'缺失'} / 配准${h.registered?'可用':'待补'}${h.stale?' / 图片需重绘':''}\n  缺少：${h.missing.join('、')||'未发现清单项缺失'}\n  自由点 ${h.point_count} 个；${h.field_report?'有提交点检查报告，非全场认证':'无现场检查报告'}`)].filter(x=>x!==null).join('\n');$('flow-export-state').textContent=changes.first_export?'本浏览器首次交付检查，全部列为新增。':'与上一次本机导出快照比较；不是与服务器已发布版本比较。';$('flow-export').disabled=false;}catch(e){$('flow-export-state').textContent=e.message;}};
  $('flow-close').onclick=()=>{if(!busy)drawer.hidden=true;};
  $('flow-export').onclick=async()=>{if(busy)return;if(!$('flow-confirm').checked){$('flow-export-state').textContent='请先确认缺失项及隐私提示。';return;}if(!api.sync())return;busy=true;$('flow-export').disabled=true;try{
    const c=structuredClone(api.course()),now=await W.snapshot(c);if(W.stable(now)!==W.stable(reviewSnapshot)){throw Error('检查后项目已有变化，请关闭并重新打开交付检查。');}
    const pack=await CourseProjects.exportPack(c);pack.delivery_review={format:'golf-delivery-review/1',created_at:new Date().toISOString(),published:false,field_verified:false,readiness:W.assess(c),changes:W.changes(now,previous()),snapshot:now};
    for(const u of urls)URL.revokeObjectURL(u);urls=[];$('flow-links').replaceChildren();for(const [name,data] of [[(c.project_id||c.slug)+'.golf-project.json',pack],[(c.project_id||c.slug)+'-delivery-review.json',pack.delivery_review]]){const u=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));urls.push(u);const a=document.createElement('a');a.href=u;a.download=name;a.textContent='下载 '+name;$('flow-links').append(a);}
    // One automatic download only; browsers may block a second. The report stays in both files.
    $('flow-links').querySelector('a').click();try{localStorage.setItem(key(),JSON.stringify(now));$('flow-export-state').textContent='交付包已生成并发起下载；请确认文件已保存。报告也包含在包内。没有上传或发布。';}catch(_){$('flow-export-state').textContent='下载已发起，但导出快照无法保存；下次会重新比较。没有上传或发布。';}
  }catch(e){$('flow-export-state').textContent=e.message;}finally{busy=false;$('flow-export').disabled=false;}};
  return {refresh};
}
