/* Workflow status is not certification. No remote writes. */
(function(root,factory){const api=factory(typeof module==='object'?require('./hd-map.js'):root.CourseHD,typeof module==='object'?require('../holemap-gps/registration.js'):root.HoleRegistration);if(typeof module==='object')module.exports=api;else root.CourseWorkflow=api;})(typeof globalThis==='undefined'?this:globalThis,function(HD,R){
  'use strict';
  function assess(c){const holes=(c.holes||[]).map(h=>{const missing=[];if(!h.holeperim?.length)missing.push('洞界');if(!h.fairway?.length)missing.push('球道');if(!h.green?.length)missing.push('果岭');if(!h.teebox?.length&&!Object.keys(h.tees||{}).length)missing.push('发球区');if(!h.cart_route?.length&&!h.cartpaths?.length)missing.push('球车道');if(!h.flag&&!h.pins?.mid)missing.push('实地旗位');if(h.par==null||h.par_status==='unknown')missing.push('PAR');
      let renderable=false;try{HD.layout(h,2048);renderable=true;}catch(_){}
      const v=h.visual,registered=!!v&&R.fit(v.controls||[],{checkpoints:v.checkpoints||[]}).valid,stale=!!v?.generator&&!HD.current(v,h);
      return {n:h.n,missing,renderable,image:!!v,registered,stale,point_count:(h.device_points||[]).length,field_verified:false,field_report:!!h.field_audit,stage:!renderable?'missing_geometry':!v?'needs_image':!registered?'needs_registration':stale?'needs_regeneration':'ready_for_review'};
    });return {holes,total:holes.length,renderable:holes.filter(h=>h.renderable).length,images:holes.filter(h=>h.image).length,needs_image:holes.filter(h=>h.renderable&&!h.image).length,ready:holes.filter(h=>h.stage==='ready_for_review').length,field_verified:false};}
  function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(x=>stable(x)??'null').join(',')+']';return '{'+Object.keys(v).sort().filter(k=>v[k]!==undefined).map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';}
  async function digest(v){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(stable(v)))),b=>b.toString(16).padStart(2,'0')).join('');}
  async function snapshot(c){const meta={...c};delete meta.holes;delete meta.revision;delete meta.updated_at;return {format:'golf-delivery-snapshot/1',project_id:c.project_id||c.slug,metadata:await digest(meta),holes:await Promise.all(c.holes.map(async h=>({n:h.n,hash:await digest(h)})))};}
  function changes(now,previous){if(!previous||previous.format!==now.format||previous.project_id!==now.project_id)return {first_export:true,added:now.holes.map(h=>h.n),changed:[],removed:[],unchanged:[],metadata_changed:false};const old=new Map(previous.holes.map(h=>[h.n,h.hash])),ns=new Set(now.holes.map(h=>h.n));return {first_export:false,added:now.holes.filter(h=>!old.has(h.n)).map(h=>h.n),changed:now.holes.filter(h=>old.has(h.n)&&old.get(h.n)!==h.hash).map(h=>h.n),unchanged:now.holes.filter(h=>old.get(h.n)===h.hash).map(h=>h.n),removed:previous.holes.filter(h=>!ns.has(h.n)).map(h=>h.n),metadata_changed:now.metadata!==previous.metadata};}
  return {assess,snapshot,changes,stable};
});
